### ISSUE TITLE
sentinel crashes on couchdb close?

### ISSUE THREAD

**Issue by mandric** [medic/medic-sentinel#56]
Should probably handle this gracefully and make sure when couchdb comes back sentinel also does.  This might also be a gardener configuration issue because it stops retrying because of a less than 2 second uptime crash.  So adding a listener for onClose and then calling a proper exit function that waits for 2 secs should do it.

```
2014-05-08T10:03:04.097Z - error: sentinel getDoc failed with error: Error: Error: socket hang up
 undefined
2014-05-08T10:03:04.115Z - error: sentinel getDoc failed with error: undefined
 undefined
2014-05-08T10:03:04.116Z - info: Changes stream ended undefined
 undefined
2014-05-08T10:03:04.288Z - error: Could not find design document [Error: Error: connect ECONNREFUSED]
 undefined
2014-05-08T10:03:04.291Z - error: 
 undefined
2014-05-08T10:03:04.291Z - error: /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L2t1anVhLWxpdGUvX2Rl
c2lnbi9rdWp1YS1saXRl/node_modules/kujua-sentinel/server.js:37 undefined
2014-05-08T10:03:04.292Z - error: tring(0, 1) === '_' || JSON.stringify(base[key]) === JSON.stringify(doc[key]);
 undefined
2014-05-08T10:03:04.294Z - error:   undefined
2014-05-08T10:03:04.294Z - error:   undefined
2014-05-08T10:03:04.295Z - error:                                                                      ^
 undefined
2014-05-08T10:03:04.300Z - error: TypeError: Cannot read property 'lib' of undefined
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L2t1anVhLWxpdGUvX2Rlc2lnbi9rdWp1YS1saXRl/node_modules/kujua-sentinel/server.js:37:99
    at Array.every (native)
    at Function._.every._.all (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L2t1anVhLWxpdGUvX2Rlc2l
nbi9rdWp1YS1saXRl/node_modules/kujua-sentinel/node_modules/underscore/underscore.js:193:62)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L2t1anVhLWxpdGUvX2Rlc2lnbi9rdWp1YS1saXRl/node_modules/kujua-sentinel/server.js:36:21
    at ClientRequest.onClose (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L2t1anVhLWxpdGUvX2Rlc2ln
bi9rdWp1YS1saXRl/node_modules/kujua-sentinel/node_modules/felix-couchdb/lib/couchdb.js:185:11)
    at ClientRequest.EventEmitter.emit (events.js:92:17)
    at Socket.socketCloseListener (http.js:1479:7)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:466:12)
 undefined
```

**Comment by mandric** [comment]
Tested on 1.1.0, gardener tries to restart processes forever.
